=== atharvac1301/Sem-6-WTL/Assignment 3/employee.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (id, name, department, salary)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== atharvac1301/Sem-6-WTL/Assignment 3/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>

<employees>
  <employee>
    <id>1</id>
    <name>John Doe</name>
    <department>Engineering</department>
    <salary>70000</salary>
  </employee>
  <employee>
    <id>2</id>
    <name>Kevin Lee</name>
    <department>Marketing</department>
    <salary>60000</salary>
  </employee>
</employees>
